# Generated by Django 4.0.3 on 2022-05-01 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program', models.TextField()),
                ('bank', models.TextField()),
                ('country', models.TextField()),
                ('currency', models.TextField(max_length=3)),
            ],
        ),
    ]
