# Generated by Django 4.0.3 on 2022-05-01 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.TextField()),
                ('currency', models.TextField(max_length=3)),
                ('program', models.TextField()),
                ('bank', models.TextField()),
                ('is_eligible', models.BooleanField(default=True)),
            ],
        ),
    ]
