# Generated by Django 4.0.3 on 2022-05-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_currency_and_more'),
        ('banks', '0002_remove_bank_countries_bank_countries'),
        ('general', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.bank'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.country'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program'),
        ),
    ]
